// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pslyruoyiuhvrxtxrrcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzbHlydW95aXVodnJ4dHhycmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTI2MDIsImV4cCI6MjA2MjEyODYwMn0.nO1VFVEvI6sRo6h695A7sO8aLHXEpBgWw95-c2a4xRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);